language: java

before_script:
  - curl http://www.jpm4j.org/install/script | sh
  - jpm install com.codacy:codacy-coverage-reporter:assembly
  - export CODACY_PROJECT_TOKEN=026fa0a6727e4d159f2ed74a110fd828
before_install:
  - pip install --user codecov
after_success:
  - codecov
  - codacy-coverage-reporter -l Java -r coverage.xml
